language: ruby
sudo: false
cache: bundler

services:
  - mysql

rvm:
  - 2.3.2

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle install
  - bin/rake db:create
  - bin/rake db:migrate
  - bin/rake db:seed
